version: "3"

services:
  server:
    build: ./
    privileged: true
    container_name: ai-associate-attorney-server-side-python-api-server
    environment:
      - NODE_ENV=production
    networks:
      - zmeet
    volumes:
      - /gt/ai-associate-attorney/py.associateattorney.ai:/gt/ai-associate-attorney/py.associateattorney.ai
      - /gt/ai-associate-attorney/py.associateattorney.ai/etc-supervisor-conf.d-services.conf:/etc/supervisor/conf.d/services.conf
    # ports: docker-compose is only used for prod. And in prod port forwarding is not needed since nginx is the proxy and its on the same network as this container.
    #  - "3000:3000"

networks:
  zmeet:
    external:
      name: zmeet_default
