FROM ubuntu:22.04

# install supervisor software
RUN apt-get update && \
 apt-get -y upgrade && \
 apt-get install -y supervisor --no-install-recommends
 
RUN apt install -y curl net-tools telnet

RUN apt install -y python3-pip

RUN pip install langchain

RUN pip install openai

RUN pip install flask

RUN pip install flask_cors

RUN pip install transformers

RUN pip install torch

RUN pip install einops

RUN pip install replicate

RUN apt install -y screen

RUN pip install mysql-connector-python

RUN pip install OpenAI

RUN pip install python-dotenv

RUN pip install fitz

RUN pip install frontend

RUN pip install PyMuPDF

RUN pip install tools
    
RUN pip install Pillow
RUN pip install Pilvo

RUN pip install pytesseract

EXPOSE 3001

CMD ["/usr/bin/supervisord", "-n","-c","/etc/supervisor/supervisord.conf"]